// swift-tools-version: 6.2

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "find pics",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "find pics",
            targets: ["FindPicsApp"],
            bundleIdentifier: "com.rezashamji.findpics",
            teamIdentifier: "YYP85AQ2C5",
            displayVersion: "0.1",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait
            ],
            capabilities: [
                .photoLibrary(purposeString: "find pics searches your photos ON this phone. Nothing is uploaded."),
                .photoLibraryAdd(purposeString: "find pics can save a search result as a new album (only when you tap Save).")
            ]
        )
    ],
    dependencies: [
        .package(path: "../FindPicsCore"),
        .package(url: "https://github.com/ml-explore/mlx-swift-lm", "3.32.3"..<"3.33.0"),
        .package(url: "https://github.com/huggingface/swift-huggingface", "0.9.0"..<"1.0.0"),
        .package(url: "https://github.com/huggingface/swift-transformers", "1.3.0"..<"2.0.0"),
        .package(url: "https://github.com/ml-explore/mlx-swift", "0.32.3"..<"0.33.0")
    ],
    targets: [
        .executableTarget(
            name: "FindPicsApp",
            dependencies: [
                "FindPicsCore",
                .product(name: "MLXVLM", package: "mlx-swift-lm"),
                .product(name: "MLXLMCommon", package: "mlx-swift-lm"),
                .product(name: "MLXHuggingFace", package: "mlx-swift-lm"),
                .product(name: "HuggingFace", package: "swift-huggingface"),
                .product(name: "Tokenizers", package: "swift-transformers"),
                .product(name: "MLX", package: "mlx-swift")
            ],
            path: "Sources",
            resources: [
                .copy("Models"),
                .copy("SelfCheck")
            ]
        )
    ]
)